name = "my-app"
compatibility_date = "2023-12-01"
# account_id = ""
compatibility_flags = ["nodejs_compat"] #for browser worker
workers_dev = true

# browser = { binding = "MYBROWSER" }
# kv_namespaces = [
#     { binding = "BROWSER_KV_DEMO", id = "59cb54fd81c64c3bac53eb733df74164" }
# ]

# r2
[[r2_buckets]]
 bucket_name = "browser-worker"
 binding = "BROWSER_BUCKET"

[[d1_databases]]
binding = "DB"
database_name = "mydb"
database_id = "3fdc2404-e010-4ef4-9b5c-bf04a44c0265"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [ai]
# binding = "AI"